version: '3.8'
services:
  builder:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        ANDROID_API_LEVEL: ${ANDROID_API_LEVEL}
        GRADLE_VERSION: ${GRADLE_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        JDK_VERSION: ${JDK_VERSION}
        BUILD_TOOLS_VERSION: ${BUILD_TOOLS_VERSION}
    volumes:
      - ./src:/usr/src/cordova
      - ./build:/usr/src/cordova/platforms/android/app/build/outputs/apk
    env_file:
      - .env
